### ISSUE TITLE
Broken demo

### ISSUE THREAD

**Issue by egorshulga** [gnaeus/react-ioc#3]
Hey @gnaeus! 
It seems it is a great lib, but as I can see the [demo](https://codesandbox.io/s/n38r0xoy24) (from your habr article) is dead.
![image](https://user-images.githubusercontent.com/6253488/58021659-27466d00-7b14-11e9-9716-501451a2f81a.png)
Is it still supported? Could you take a look?
Thanks!

**Comment by gnaeus** [comment]
Sorry! This demo is based on [create-react-app-typescript](https://github.com/wmonk/create-react-app-typescript), which is now deprecated.

So I port this demo to vanilla parcel template.
