### ISSUE TITLE
toFactory for non mst classes

### ISSUE THREAD

**Issue by thisroot** [gnaeus/react-ioc#6]
Thanks for great library!
I have suggestion. Can you add toFactory method for none mst classes? The good idea append function same  `dispose()` but only create instance life cycle event.

**Comment by gnaeus** [comment]
Sorry for long wait!

`toFactory` method doesn't force you to use MST. It designed to create any dependencies wor which we can't use class constructors. For example, MST models.

And I can't clearly understand your idea about `dispose` method. Can you explain it by code example?
