### ISSUE TITLE
Use store inside of service

### ISSUE THREAD

**Issue by bushukhina** [gnaeus/react-ioc#7]
I want to use react-ioc in my typescript app, injection in this code doesn't work

`
import { observable } from 'mobx
import { provider, inject } from 'react-ioc'`

There are  some React.Components
`@ provider(OuterService )`
`export class Component extends React.Component {`
`   @ inject outerService : OuterService ;`
`    render() {`
`      // ...`
`    }`
}`

And to services

`@ provider(InnerService )`
`export OuterService {`
`   innerService: InnerService;`
`
`   contructor() {`
`       this.innerService = inject(this, InnerService );`
`   }`

  // methods
}`

`@ provider(MyStore )`
`export InnerService {`
`   myStore : MyStore ;`

`   contructor() {`
`       this.myStore = inject(this, MyStore );`
`   }`
`   //methods`
`}`

And store with observable fields

`export default class MyStore {`
`    @ observable `
`    fild?: string;`
`    ....`
`}`

@gnaeus  Injection of OuterService in Component  works, but how correctly inject InnerService into OuterService, and MyStore  into InnerService?? Is it possible?
Store should be created only once, services don't have to, but im not sure scince they inject store

**Comment by gnaeus** [comment]
@bushukhina,  `@provider` decorator intended to be used only with React components, not with any other classes. And if we register some service in some component through `@provider`, then a single instance of this service will be available for injection form entire components subtree (starting from our component).

So your example should look like:

```js
import { observable } from 'mobx';
import { provider, inject } from 'react-ioc';

export class MyStore {
  @observable field?: string;
}

export class InnerService {
  @inject myStore: MyStore;
}

export OuterService {
  @inject innerService: InnerService;
}

@provider(OuterService, InnerService, MyStore)
export class Component extends React.Component {
  @inject outerService: OuterService;

  render() {
    // ...
  }
}
```

**Comment by bushukhina** [comment]
That decided my problem
