### ISSUE TITLE
Inject into withRouter/Router component

### ISSUE THREAD

**Issue by bushukhina** [gnaeus/react-ioc#8]
I have some component that is exported inside of withRoute() HOC, 
it is also suitable to use <Router ... />.

Is it possible to inject into such component?

`export class MyStore {
  @observable field?: string;
}

@provider( MyStore)
class MyComponent extends React.Component {
  @inject outerService: OuterService;

  render() {
    // ...
  }
}

export default withRouter(MyComponent );
`

**Comment by bushukhina** [comment]
> I have some component that is exported inside of withRoute() HOC,
> it is also suitable to use <Router ... />.
> 
> Is it possible to inject into such component?
> 
> `export class MyStore {
> @observable field?: string;
> }
> 
> @Provider( MyStore)
> class MyComponent extends React.Component {
> @Inject outerService: OuterService;
> 
> render() {
> // ...
> }
> }
> 
> export default withRouter(MyComponent );
> `

@gnaeus , can you give your recommendation?

**Comment by gnaeus** [comment]
But what is the question? Of course you can use react-router and react-ioc together:

```jsx
@Provider(MyStore)
class MyComponent extends React.Component {
  @Inject myStore: MyStore;

  render() {
    return <SubComponent />;
  }
}

export default withRouter(MyComponent);
```
This should work too:
```jsx
class SubComponent extends React.Component {
  @Inject myStore: MyStore;

  render() {
    // ...
  }
}

export default withRouter(SubComponent);
```

**Comment by bushukhina** [comment]
Basically, the question is: "Why can it be that this does not work?"

**Comment by bushukhina** [comment]
Just found out that problem was with constuctor of extended React.Component(the very first component in the inheritance  chain), I deleted it and it works
